services:
    mosquitto-broker:
        image: eclipse-mosquitto:latest
        ports:
            - 1883:1883
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        
    influx-logger:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PYTHONUNBUFFERED: 1
            MQTT_URL: mosquitto-broker
            MQTT_PORT: 1883
            INFLUXDB_BUCKET: weather_test_data
            INFLUXDB_URL: influxdb2
            INFLUXDB_ORG: university-of-oulu
            INFLUXDB_USERNAME: admin
            INFLUXDB_PASSWORD: admin123
        depends_on:
            - mosquitto-broker
            - influxdb2
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        
    influxdb2:
        image: influxdb:2
        ports:
        - 8086:8086
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: admin
            DOCKER_INFLUXDB_INIT_PASSWORD: admin123
            DOCKER_INFLUXDB_INIT_ORG: university-of-oulu
            DOCKER_INFLUXDB_INIT_BUCKET: weather_test_data

    grafana:
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        environment:
            - GF_SECURITY_ALLOW_EMBEDDING: "true"
        depends_on:
            - influxdb2
